class AutomationState:
    NOT_INITIALIZED = -1
    INITIALIZED = 0
    ROOF_OPENING = 1
    ROOF_OPENED = 2
    MOVING_POSITIONERS_APART = 3
    MOVED_POSITIONERS_APART = 4
    SLIDING_OFF_POSITIONERS = 5
    POSITIONERS_SLIDED_OFF = 6
    CLOSING_ROOF = 7
    ROOF_CLOSED = 8
