class DevicesStringDescriptors:
    TEMPERATURE_AND_HUMIDITY_SENSOR_ID = '0E650C010D86'
    RAIN_SENSOR_ID = '085BBA4C0240'
    WIND_SENSOR_ID = '0B4A1F05E7BA'


class DevicesIntDescriptors:
    TEMPERATURE_AND_HUMIDITY_SENSOR_ID = 0
    RAIN_SENSOR_ID = 1
    WIND_SENSOR_ID = 2
